### ISSUE TITLE
补全问题

### ISSUE THREAD

**Issue by e190** [zbelial/lspce#1]
补全的时候，会把其他信息一起填进去。
![图片](https://user-images.githubusercontent.com/39932163/174511867-c9bdffbf-c02f-4860-9de6-f1340676a5cf.png)
像这个图片里面 的参数 （...）原封不动的补全了。
![图片](https://user-images.githubusercontent.com/39932163/174512024-8d6f7236-9020-4277-946f-90278fbb9333.png)
![图片](https://user-images.githubusercontent.com/39932163/174512089-bfd74256-477a-4ee2-9001-95eba8e2ab20.png)

(as Into) 也 填上了。

**Comment by zbelial** [comment]
补全刚实现的时候确实是这样的，但是后来改了（而且改了有一段时间了），所以我怀疑你用的不是最近的代码。

另外你是用的company还是corfu？我不用corfu，所以只测试过company。

**Comment by zbelial** [comment]
用corfu确实会有你说的这个问题，今天试着修复了一下，你可以再试试。
感谢反馈。
