### ISSUE TITLE
Automatic venv activation with pyright + lspce

### ISSUE THREAD

**Issue by alkurbatov** [zbelial/lspce#41]
Ok, back to the virtualenv world :(

1. Assume I have a `.venv` folder located in the root of my project.
2. If i do `./venv/bin/activate` and run Emacs, lspce runs pyright in the venv of the project and all features work just fine.

Now I want to automate this setup. One of possible approaches is to create pyrightconfig.json with the following content:
```json
{
  "include": [
    "tttt"
  ],
  "exclude": [
    "**/__pycache__"
  ],

  "pythonVersion": "3.12",
  "pythonPlatform": "Darwin",

  "venvPath": "/Users/alkurbatov/work/src/github.com/alkurbatov/tttt",
  "venv": ".venv"
}
```

Please, pay attention to the `venvPath` and `venv`. It sets direct path to virtualenv.
This approach works with eglot without any tweaks but not with lspce.

**Comment by alkurbatov** [comment]
Also, I found that eglot recognizes local venvs (i.e. located in files named `.venv` in the root of the project). This is convenient too, but the best thing would be to support pyright config as tools like poetry could story venvs somewhere else.

**Comment by zbelial** [comment]
Thanks for providing these info, but I think I need to learn more about pyright and how to configure it.  I'll ping you when I have something positive.

**Comment by zbelial** [comment]
It should work now, so closing this issue.
