### ISSUE TITLE
Is it possible to manually update the diagnostics? 

### ISSUE THREAD

**Issue by WeissP** [zbelial/lspce#42]
Sometimes diagnostics didn't display in time, and may even disappear after `apheleia-format-buffer` is invoked (which comes from [apheleia](https://github.com/radian-software/apheleia)).

So I would like to know whether there is a way to manually update diagnostics?

**Comment by zbelial** [comment]
Does invoking `flymake-start` work for you?  
But sometimes lsp servers need a period of time(hundreds of milliseconds or even seconds) to regenerate diagnostics, you need wait and then manually update.

**Comment by zbelial** [comment]
I use the following config, it works most of the time. 
```elisp
            (setq flymake-no-changes-timeout 1.0)
            (setq flymake-start-on-flymake-mode nil)

            (add-hook 'flymake-mode-hook
                      (lambda () (run-with-idle-timer flymake-no-changes-timeout t #'flymake-start)))

```

Maybe there is some bug somewhere in lspce though.

**Comment by WeissP** [comment]
Here is a little experiment I just did:
1. Write something nonsense that cannot compile.
2. invoke `save-buffer` 
3. wait a few seconds
4. invoke `save-buffer` again

The error only appears after step 4, even nothing is changed after step 1.

I guess that means after the first `save-buffer`, the lsp server starts to generate diagnostics, but they will not appear until I invoke  `save-buffer` again?


In this mean time, I solved this by adding a advice for `apheleia-format-buffer` to invoke `(run-with-timer 2 nil #'flymake-start)`. On my computer, it seems that 2 seconds is the minimum time required to display the regenerated diagnostics.

**Comment by zbelial** [comment]
It depends on the lsp server you are using and how you configure flymake IMO. 

This is how lspce deals with diagnostics:
1. After you modify a file, lspce will send the changes to the lsp server
2. lsp server will generate diagnostics 
3. if there is any, lsp server publish these diagnostics to lspce
4. lspce's rust code will cache these diagnostics
5. flymake call `flymake-diagnostic-functions` (in lspce, it is `lspce-flymake-backend`) to retrieve diagnostics and display them. 

So if step 1-4 works without problems, when and how to display the diagnostics depends on flymake.

**Comment by WeissP** [comment]
Okay Thanks for the information. I will then try to learn more about flymake.
